### ISSUE TITLE
Mögliche Kooperation

### ISSUE THREAD

**Issue by JeremyTheocharis** [thomas-v2/S7CommPlusDriver#1]
Hi Thomas,

wir haben das Projekt soeben entdeckt und sind auf der Suche nach einer kritischen Masse an Personen, die Interesse haben eine Bibliothek für S7CommPlus zu entwickeln. Du bist bereits aktiv dran. Hättest du Lust dich hierzu einmal auszutauschen?

Zum Hintergrund: Wir bieten den gesamten IT / OT Stack Open-Source an (https://github.com/united-manufacturing-hub/united-manufacturing-hub) und sind gerade dabei typische Manufacturing Konnektoren zu vereinfachen, sodass diese sich sehr leicht für die IT mit Docker, etc. verwalten lassen und die Daten über gängigere Formate wie HTTP, MQTT, Kafka, etc. bereit zu stellen. Wir haben dies auch bereits mit OPC-UA gemacht: https://github.com/united-manufacturing-hub/benthos-umh

Melde dich gerne, wenn du Interesse hast!

Viele Grüße
Jeremy

**Comment by thomas-v2** [comment]
Hallo Jeremy,

wir können uns gerne austauschen um eine Lösung zu finden, die dann in möglichst vielen anderen Anwendungen zum Einsatz kommen kann, ich denke da z.B. auch an Node-Red. Meiner Meinung nach fährt man mit einer C-Api am Besten, weil das vermutlich von fast allen Programmiersprachen angesprochen werden kann. Meine C#-Variante hier ist nur ein Ansatz um eine OpenSource-Lösung überhaupt mal ins Rollen zu bringen, da ich Teile davon aus anderen Gründen schon fast fertig hatte. Aktuell ist bei der Entwicklung auch noch etwas "Forschungsarbeit" notwendig, um herauszufinden wie einige Dinge im Protokoll überhaupt konkret funktionieren.

Was würde für euer Projekt denn passen?
