### ISSUE TITLE
Probleme beim Browsen

### ISSUE THREAD

**Issue by Nick135** [thomas-v2/S7CommPlusDriver#10]
Hallo Thomas,

ich versuche gerade die Lib zu verstehen und habe an einer SINUMERIK ONE NCU 1760 mit S7-1500 einen Datenbaustein hinzugefügt und erwartet, dass dieser durch Browsen gefunden wird. Dem ist jedoch nicht so.
Es werden jedoch Standardbausteine der SINUMERIK gefunden.

|  |  |
| - | - |
| NCU | 1760 |
| Artikel-Nr. | 6FC5 317-6AA00-0Axx |
| Firmware | V6.20 |
|  |  |
| CPU | 1500 |
| Artikel-Nr. | 6FC5 518-4FP00-6AB0 |
| Firmware | V2.9 |
| TIA | V17 |

![image](https://github.com/thomas-v2/S7CommPlusDriver/assets/14072733/763a24e0-c5f3-4aa4-ad93-8f663f9b53e6)

![image](https://github.com/thomas-v2/S7CommPlusDriver/assets/14072733/99290c65-76b3-4cb3-9648-0ad9e85d15d8)

```
List<VarInfo> vars = new List<VarInfo>();
res = conn.Browse(out vars);
// Browse res => 0
// vars.Count => 2616
// vars.Where(f=>f.Name.ToLower().Contains("plus")).Count() => 0
vars.Where(f=>f.Name.ToLower().Contains("dummy")).Count() => 0
```

**Comment by thomas-v2** [comment]
Ich habe noch nie eine Aufzeichnung zu einer Sinumerik NCU im S7CommPlus Protokoll gesehen. Es könnte sein, dass hier die Datenbausteine eine andere ClassId besitzen. Bei den normalen Steuerungen setzt sich diese aux 0x8a0eXXXX zusammen, wobei XXXX dann die Datenbausteinnummer ist.

In der jetzigen Browse() Funktion wo alles aus der Steuerung in einem Rutsch abgefragt wird, werfe ich aus der Antwort alle Objekte mit einer anderen ClassId raus. Da wäre zu prüfen, ob a) die Datenbausteine in der Antwort überhaupt vorhanden sind, und b) wenn ja, welche ClassId diese besitzen.

Man könnte die Informationen auch über das Programm dumpen, aber einfacher ist das meiner Meinung nach an einer Wireshark Aufzeichnung zu analysieren. Wenn ich mir das mal ansehen soll, bitte eine Wireshark Aufzeichnung vom browsen erstellen, und wie auf der Startseite beschrieben in die pcapng die TLS Schlüssel integrieren. Wenn du die Daten hier nicht anhängen möchtest, kannst du mir diese auch per Mail zukommen lassen.

**Comment by Nick135** [comment]
@thomas-v2 Hab dir gerade ne Mail geschickt.

**Comment by Nick135** [comment]
DB kommt an. Dann wird es wohl am Auslesen der Variablen Namen scheitern, oder ich hab das mit "vars.Name" falsch verstanden.

![image](https://github.com/thomas-v2/S7CommPlusDriver/assets/14072733/41234b10-636a-4196-87b9-d2c42d4ce801)

**Comment by thomas-v2** [comment]
Der Name kommt schon bei der ersten Anfrage zurück. Im zweiten Schritt werden dann die Typ-Informationen abgefragt, d.h. der Aufbau des DBs sowie aller Datentypen und FBs, und das ist bei dir ein ziemlich großer Datensatz. Vielleicht schlägt dort etwas fehl.

Ich habe die Funktionen zum Abfragen einzelner Bausteine schon integriert. Ich kann dir mal eine Testversion zukommen lassen, bei der das schon unter einer rudimentären GUI bedienbar ist.

**Comment by Nick135** [comment]
Ich hab bei den exploreData jetzt nur den einen DB hinzugefügt.
Dennoch enthält die varInfoList nicht die Variablen des DBs. varInfoList ist jetzt null. Wireshark wieder als Mail.

![image](https://github.com/thomas-v2/S7CommPlusDriver/assets/14072733/79cce283-2774-486b-8d2c-206653d5e5f2)

**Comment by thomas-v2** [comment]
Ich denke, das meiste was diesen Fall betrifft, sollte behoben sein.
