### ISSUE TITLE
OpenSSL connection error

### ISSUE THREAD

**Issue by stinger0698** [thomas-v2/S7CommPlusDriver#41]
For some reason, when i run communication with PLC as windows service, after couple minutes it throw following error. 
![image](https://github.com/user-attachments/assets/0cfaae44-1e94-4878-8a4e-6be6a478889a)
For some reason it cant find function in libcrypto-3-64x.dll. Perhaps someone has faced such a problem.

Wireshark log:
[s7CommPlus.zip](https://github.com/user-attachments/files/17011013/s7CommPlus.zip)

**Comment by thomas-v2** [comment]
Maybe when running as a service, your application doesn't search in the application directory, but in the standard locations. For a test, you can try to add the path where the dll is located to the system variable "PATH". Copying in to windows/system32 path would also be an option, but to dump dll's there without a install/deinstall routine is not a good way.

**Comment by stinger0698** [comment]
Well i tried to check libcrypto-3-64x.dll export table with dumpbin and it seems 'BIO_should_retry' is not in it.
![image](https://github.com/user-attachments/assets/858cc1be-8a79-48ad-87ed-f2fa441c623c)
Perhaps it is possible to handle error in some other way at SendPendingData() at OpenSSLConnector.cs?

**Comment by thomas-v2** [comment]
You're correct, BIO_should_retry is in the bio.h only a define for another method with a defined parameter. I don't know why this never occured as error. I'll check for other defines which I haven't seen, and make a change.

**Comment by thomas-v2** [comment]
You can try if the latest change fixes also your problem.

**Comment by stinger0698** [comment]
Thank you, worked for couple days without any problem.
