### ISSUE TITLE
Inconsistent data type with PLC

### ISSUE THREAD

**Issue by Siriling** [thomas-v2/S7CommPlusDriver#48]
Hello, I've discovered an issue while using it. Specifically, there's a discrepancy between the data types in the PLC and those obtained through this driver.

I can check the data type serial number through the following code:
```c++
private void treeView1_AfterExpand(object sender, TreeViewEventArgs e)
{
......
    for (int i = 0; i < pObj.VarnameList.Names.Count; ++i)
    {
        Console.WriteLine("0:{0}", pObj.VarnameList.Names[i]);
        Console.WriteLine("1:{0}", pObj.VartypeList.Elements[i].Softdatatype);
......
}
```

![image](https://github.com/user-attachments/assets/879eeefd-88af-4726-89bf-8f53d7a29200)

The correct data type number should be 131

```c++
public const uint S7COMMP_SOFTDATATYPE_EVENTHWINT = 131;
```

**Comment by thomas-v2** [comment]
Confirmed, there's something wrong with the type id for at least this type.

**Comment by Siriling** [comment]
The issue has been resolved after updating the code. Thank you very much!
