### ISSUE TITLE
Connect fehlgeschlagen S7-1518

### ISSUE THREAD

**Issue by Nick135** [thomas-v2/S7CommPlusDriver#6]
Bei mir schlägt bereits der Verbindungsaufbau zu einer S7-1518 fehl.

|  |  |
| ------------- | ------------- |
| CPU | 1518TF-4 PN/DP |
| Artikel-Nr. | 6ES7 518-4UP00-0AB0 |
| Hardware | 10 |
| Firmware | V2.9.2 |
| TIA | V17 |

```
Main - START
Main - Versuche Verbindungsaufbau zu: 192.168.214.100
Main - Connect fehlgeschlagen!
Main - ENDE. Bitte Taste drücken.
```

![image](https://github.com/thomas-v2/S7CommPlusDriver/assets/14072733/0ae4913c-0f5a-4aa4-b1cc-c6e6e9ebaa83)

[S71518_Connect.zip](https://github.com/thomas-v2/S7CommPlusDriver/files/13249239/S71518_Connect.zip)

Per OPC-UA komm ich auf die PLC.

**Comment by thomas-v2** [comment]
Hallo,

hast du OpenSSL, bzw. die notwendigen Bibliotheken installiert?

Siehe:
https://github.com/thomas-v2/S7CommPlusDriver#openssl

**Comment by Nick135** [comment]
"OpenSSL in der entsprechenden Version installiert": Welche Version?

Hab jetzt die x64 Version 3.1.2.0 der beiden dll mit da zu gelegt. Will jedoch immer noch nicht.

![image](https://github.com/thomas-v2/S7CommPlusDriver/assets/14072733/4b3f8283-1dc2-4c7e-8e8c-31abc0a473af)

**Comment by Nick135** [comment]
Problem Gefunden:
Dll hieß "libcrypto_3_x64.dll" und nicht "libcrypto-3-x64.dll"

**Comment by thomas-v2** [comment]
Kam die dll mit Unterstrich aus deiner Installation, oder selber umbenannt? Nur damit ich weiß, ob ich an der Dokumentation bzw. am Namen der dll im Code noch etwas anpassen sollte.

**Comment by Nick135** [comment]
Hab die dll aus dem OpenVPN Ordner genommen. Dort liegen se mit Unterstrich.
