### ISSUE TITLE
Generating Certificates and Implementing TLS Encryption on S7-1200/1500

### ISSUE THREAD

**Issue by bbovbjerg** [thomas-v2/S7CommPlusDriver#7]
Hi Thomas,

I have downloaded the S7CommPlus project and would like to establish communication to a S7-1500 PLC.
I am a beginner in OpenSSL/TLS, but have been working with PLC drivers on Windows for many years
For me it is not clear what I must configure on the TIA Portal to activate TLS encryption and generate certificates.

I have read this blog: "S71200/1500 TLS Encryption: How to Secure Your Industrial Network"
(https://www.dmcinfo.com/latest-thinking/blog/id/10181/s712001500-tls-encryption-how-to-secure-your-industrial-network).
Is this blog valid when using S7CommPlus  on MS Windows ? - or can you show me another guide ?

Best regards,
Bent B

**Comment by thomas-v2** [comment]
Hi Bent,

the blog is not exactly valid for S7CommPlus. But you can also create your own certificates for the CPU, which is almost similar to how it's described there. At the moment the certificates aren't checked, means the program accepts all certificates whithout a check. That's one thing which has to be added later, but it's not on my hich priority.

So you can keep the default settings when you create project whithout creating your own certificates. In the background TIA creates it's own signed certificate, which is Ok for know. If you want to test this library, it'll only work without CPU password protection (for now).
