### ISSUE TITLE
Issue in POffsetInfoType.cs

### ISSUE THREAD

**Issue by DamienPim** [thomas-v2/S7CommPlusDriver#8]
Hello Thomas,
I found an issue in POffsetInfoType.cs.
lines 150 to 154 are a copy of lines 144 to 148 and I think it is an error.
If I comment these lines, it is working with my PLC Program. If not, there is a shift in the buffer and the analyze is troncated.
Hope this help.

Damien.

**Comment by thomas-v2** [comment]
Hi Damien,
thank you for finding this. Fixed.

I'm just working on a more specific kind of explore method, where I don't readout many data which isn't needed for variable access. I guess the error occured on exploring the plc, where also ProgramAlarm configuration is readout. I don't used them in my test projects so far.
